# Análisis de Datos de un Sensor de Temperatura

### Tenemos datos de temperatura registrados cada hora en diferentes sensores durante una semana. Usaremos NumPy para:

### - Generar datos aleatorios de temperatura.
### - Aplanar los arreglos para facilitar análisis.
### - Concatenar datos de diferentes sensores.
### - Cambiar la forma para organizar los datos por días.
### - Aplicar indexación y slicing para extraer información.
### - Manejar tipos de datos.

## 1. Generar datos aleatorios

Generamos datos de temperatura simulados para 3 sensores durante una semana (7 días, 24 horas por día).

In [66]:
import numpy as np

# Fijar semilla para reproducibilidad
np.random.seed(42)


# Generar datos aleatorios de temperatura (en °C) para 3 sensores (7 días x 24 horas)
sensor1 = np.random.randint(16,32, (7,24))
sensor2 = np.random.randint(16,32, (7,24))
sensor3 = np.random.randint(16,32, (7,24))
print('Sensor 1')
print(sensor1)
print('Sensor 2')
print(sensor2)
print('Sensor 3')
print(sensor3)
# Mostrar una muestra de datos del primeri día
muestra = sensor1[1,:]
print('Muestra')
print(muestra)

Sensor 1
[[22 19 28 30 26 23 28 20 22 25 18 22 26 26 23 20 19 23 23 18 21 20 17 23]
 [27 29 21 17 31 27 20 16 27 25 21 28 27 24 16 26 26 30 25 31 27 27 31 30]
 [29 29 30 29 18 27 22 19 31 24 18 20 18 22 20 24 22 17 19 24 27 29 17 25]
 [24 25 20 17 19 27 30 27 22 27 28 23 30 18 29 16 19 17 23 19 17 29 21 21]
 [25 19 21 28 30 17 25 27 17 25 29 19 29 30 31 30 23 29 22 27 24 29 23 20]
 [31 28 17 30 20 23 25 24 27 27 27 28 24 28 30 28 16 24 22 24 23 16 27 23]
 [23 30 26 18 16 23 18 18 16 26 20 25 22 25 24 27 22 24 23 27 17 16 31 22]]
Sensor 2
[[22 29 23 20 18 27 23 21 26 18 16 18 20 30 29 18 16 20 25 22 30 29 22 26]
 [24 30 30 25 25 27 28 18 30 31 22 16 19 28 31 19 29 20 22 22 28 30 26 28]
 [19 28 31 22 26 18 21 27 17 25 28 29 24 20 21 27 27 27 27 19 29 29 26 31]
 [25 22 27 24 22 29 16 16 24 26 29 24 19 28 24 18 22 21 23 26 24 29 20 16]
 [18 25 27 23 30 26 21 31 31 23 24 19 16 29 16 25 19 27 29 22 17 18 16 20]
 [16 23 16 26 16 17 17 27 21 22 20 31 16 16 18 29 17 20 27 25 31 21 31 22]
 [19 2

## 2. Aplanar los datos

Convertir la matriz de (7,24) en un arreglo de 168 valores (7 días x 24 horas).

In [22]:

# sensor_1_flat = sensor_1.ravel()
arr = sensor1.flatten()
arr




array([22, 19, 28, 30, 26, 23, 28, 20, 22, 25, 18, 22, 26, 26, 23, 20, 19,
       23, 23, 18, 21, 20, 17, 23, 27, 29, 21, 17, 31, 27, 20, 16, 27, 25,
       21, 28, 27, 24, 16, 26, 26, 30, 25, 31, 27, 27, 31, 30, 29, 29, 30,
       29, 18, 27, 22, 19, 31, 24, 18, 20, 18, 22, 20, 24, 22, 17, 19, 24,
       27, 29, 17, 25, 24, 25, 20, 17, 19, 27, 30, 27, 22, 27, 28, 23, 30,
       18, 29, 16, 19, 17, 23, 19, 17, 29, 21, 21, 25, 19, 21, 28, 30, 17,
       25, 27, 17, 25, 29, 19, 29, 30, 31, 30, 23, 29, 22, 27, 24, 29, 23,
       20, 31, 28, 17, 30, 20, 23, 25, 24, 27, 27, 27, 28, 24, 28, 30, 28,
       16, 24, 22, 24, 23, 16, 27, 23, 23, 30, 26, 18, 16, 23, 18, 18, 16,
       26, 20, 25, 22, 25, 24, 27, 22, 24, 23, 27, 17, 16, 31, 22])

## 3. Concatenar los datos de los sensores

Juntamos los datos de los 3 sensores para tener una matriz más grande.


In [24]:
# datos_concatenados = np.concatenate((sensor_1_flat, sensor_2.flatten(), sensor_3.flatten()))
sensores = np.concatenate((sensor1, sensor2, sensor3))
sensores


array([[22, 19, 28, 30, 26, 23, 28, 20, 22, 25, 18, 22, 26, 26, 23, 20,
        19, 23, 23, 18, 21, 20, 17, 23],
       [27, 29, 21, 17, 31, 27, 20, 16, 27, 25, 21, 28, 27, 24, 16, 26,
        26, 30, 25, 31, 27, 27, 31, 30],
       [29, 29, 30, 29, 18, 27, 22, 19, 31, 24, 18, 20, 18, 22, 20, 24,
        22, 17, 19, 24, 27, 29, 17, 25],
       [24, 25, 20, 17, 19, 27, 30, 27, 22, 27, 28, 23, 30, 18, 29, 16,
        19, 17, 23, 19, 17, 29, 21, 21],
       [25, 19, 21, 28, 30, 17, 25, 27, 17, 25, 29, 19, 29, 30, 31, 30,
        23, 29, 22, 27, 24, 29, 23, 20],
       [31, 28, 17, 30, 20, 23, 25, 24, 27, 27, 27, 28, 24, 28, 30, 28,
        16, 24, 22, 24, 23, 16, 27, 23],
       [23, 30, 26, 18, 16, 23, 18, 18, 16, 26, 20, 25, 22, 25, 24, 27,
        22, 24, 23, 27, 17, 16, 31, 22],
       [22, 29, 23, 20, 18, 27, 23, 21, 26, 18, 16, 18, 20, 30, 29, 18,
        16, 20, 25, 22, 30, 29, 22, 26],
       [24, 30, 30, 25, 25, 27, 28, 18, 30, 31, 22, 16, 19, 28, 31, 19,
        29, 20, 22, 22, 

## 4. Cambiar la forma de los datos

Reorganizamos los datos en una matriz de (7 días, 24 horas, 3 sensores) para facilitar el análisis.

In [34]:
# Mostrar del primer dia, las primeras dos horas de los 3 sensores

sensor_1 = sensor1[0,0:2]
sensor_2 = sensor2[0,0:2]
sensor_3 = sensor3[0,0:2]
print(f"Primeras 2 horas del primer dia del sensor 1: {sensor_1}")
print(f"Primeras 2 horas del primer dia del sensor 2: {sensor_2}")
print(f"Primeras 2 horas del primer dia del sensor 3: {sensor_3}")


Primeras 2 horas del primer dia del sensor 1: [22 19]
Primeras 2 horas del primer dia del sensor 2: [22 29]
Primeras 2 horas del primer dia del sensor 3: [28 18]


## 5. Indexación y slicing

Extraer información especifica

In [52]:
# Temperatura del sensor 2, día 3, hora 12
sl = sensor2[2,11]
print(sl)


# Datos del día 5 para todos los sensores
data = sensor1[4,0:], sensor2[4,0:], sensor3[4,0:]
print('Dia 5 de los 3 sensores')
for a in data:
    print(a)

29
Dia 5 de los 3 sensores
[25 19 21 28 30 17 25 27 17 25 29 19 29 30 31 30 23 29 22 27 24 29 23 20]
[18 25 27 23 30 26 21 31 31 23 24 19 16 29 16 25 19 27 29 22 17 18 16 20]
[20 31 19 23 31 23 22 18 16 31 16 31 27 26 18 21 22 21 29 29 21 21 28 18]


## 6. Convertir tipos de datos

Para ahorrar memoria, convertimos los datos de float64 a float32



In [72]:
sensor1 = np.array(sensor1, dtype=np.float32)
print(sensor1.dtype)
sensor2 = np.array(sensor2, dtype=np.float32)
print(sensor2.dtype)
sensor3 = np.array(sensor3, dtype=np.float32)
print(sensor3.dtype)

float32
float32
float32
